### ISSUE TITLE
Retrieving Quality Measures

### ISSUE THREAD

**Issue by andrewlangman** [cyberwitch/national-guideline-clearinghouse#1]
This is fantastic! Many thanks. Can you do the same for www.qualitymeasures.ahrq.gov, which is also shutting down?

**Comment by cyberwitch** [comment]
@andrewlangman Thanks for the suggestion!  Will do my best :+1:

**Comment by cyberwitch** [comment]
@andrewlangman Here you go: https://github.com/cyberwitch/national-quality-measures-clearinghouse
